
server:
  port: 8888
spring:
  application:
    name: provider-ticket2

eureka:
  instance:
    prefer-ip-address: true # 注册服务时使用服务的IP地址
  client:
    service-url:
      #注册到这个地址
      defaultZone: http://localhost:8761/eureka/