#management:
#  endpoints:
#    web:
#      path-mapping: {"beans":"/beans"}


#健康检查
management:
  endpoints:
    web:
      exposure:
        #默认只加载了info、health
        include: 'prometheus,info,health'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false

server:
  port: 8080

#spring:
#  redis:
#    host: 192.168.1.109