
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
  #配置jpa
  jpa:
    hibernate:
      ddl-auto: update # 更新或者创建表结构

    show-sql: true # 显示发送的sql语句
