# 配置数据源
#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.1.109:3306/mybatis?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
##    url: jdbc:mysql://192.168.1.109:3306/mybatis
#    driver-class-name: com.mysql.jdbc.Driver
##    type: com.alibaba.druid.pool.DruidDataSource
#    schema:
#      - classpath:tb_department.sql
#      - classpath:tb_employee.sql


spring:
  datasource:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8&characterEncoding=utf-8
      username: root
      password: root
      #初始化时建立物理连接的个数
      initial-size: 5
      #最大连接池数量
      max-active: 10
      #最小连接池数量
      min-idle: 5
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 超过时间限制是否回收
      removeAbandoned: true
      # 当连接超过3分钟后会强制进行回收
      removeAbandonedTimeout: 180
      #      打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #      间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 60000
      #用来检测连接是否有效的sql 必须是一个查询语句。mysql中为 select 'x'， oracle中为 select 1 from dual
      validation-query: select 'x'
      # validation-query-timeout: 5000
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      test-while-idle: true
      #通过connectProperties属性来打开mergeSql功能，慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #filters: #配置多个英文逗号分隔(统计，sql注入)
      filters: stat,wall
      #配置stat-view-servlet
      stat-view-servlet:
        #允许开启监控
        enabled: true
        #监控面板路径
        url-pattern: /druid/*
